// Generated by scripts/fetch-fonts.mjs from fonts.json. Do not edit.
window.STORYLOOM_BUNDLED_FONTS = [
  {
    "key": "andika",
    "label": "Andika (easy reading)",
    "category": "sans-serif",
    "family": "Storyloom Andika",
    "css": "\"Storyloom Andika\", system-ui, sans-serif",
    "files": [
      {
        "file": "andika-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "andika-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "andika-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "andika-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "andika-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "andika-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "andika-700-italic-latin.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "andika-700-italic-latin-ext.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "atkinson",
    "label": "Atkinson (clear)",
    "category": "sans-serif",
    "family": "Storyloom Atkinson Hyperlegible",
    "css": "\"Storyloom Atkinson Hyperlegible\", system-ui, sans-serif",
    "files": [
      {
        "file": "atkinson-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "atkinson-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "atkinson-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "atkinson-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "atkinson-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "atkinson-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "atkinson-700-italic-latin.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "atkinson-700-italic-latin-ext.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "nunito",
    "label": "Nunito (soft sans)",
    "category": "sans-serif",
    "family": "Storyloom Nunito",
    "css": "\"Storyloom Nunito\", system-ui, sans-serif",
    "files": [
      {
        "file": "nunito-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "nunito-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "nunito-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "nunito-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "nunito-800-normal-latin.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "nunito-800-normal-latin-ext.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "nunito-800-italic-latin.woff2",
        "weight": 800,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "nunito-800-italic-latin-ext.woff2",
        "weight": 800,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "quicksand",
    "label": "Quicksand (light round)",
    "category": "sans-serif",
    "family": "Storyloom Quicksand",
    "css": "\"Storyloom Quicksand\", system-ui, sans-serif",
    "files": [
      {
        "file": "quicksand-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "quicksand-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "quicksand-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "quicksand-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "fredoka",
    "label": "Fredoka (round)",
    "category": "sans-serif",
    "family": "Storyloom Fredoka",
    "css": "\"Storyloom Fredoka\", system-ui, sans-serif",
    "files": [
      {
        "file": "fredoka-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "fredoka-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "fredoka-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "fredoka-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "baloo",
    "label": "Baloo (bouncy)",
    "category": "display",
    "family": "Storyloom Baloo 2",
    "css": "\"Storyloom Baloo 2\", system-ui, sans-serif",
    "files": [
      {
        "file": "baloo-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "baloo-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "baloo-800-normal-latin.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "baloo-800-normal-latin-ext.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "lora",
    "label": "Lora (book serif)",
    "category": "serif",
    "family": "Storyloom Lora",
    "css": "\"Storyloom Lora\", Georgia, serif",
    "files": [
      {
        "file": "lora-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "lora-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "lora-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "lora-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "lora-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "lora-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "lora-700-italic-latin.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "lora-700-italic-latin-ext.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "literata",
    "label": "Literata (classic book)",
    "category": "serif",
    "family": "Storyloom Literata",
    "css": "\"Storyloom Literata\", Georgia, serif",
    "files": [
      {
        "file": "literata-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "literata-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "literata-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "literata-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "literata-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "literata-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "literata-700-italic-latin.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "literata-700-italic-latin-ext.woff2",
        "weight": 700,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "merriweather",
    "label": "Merriweather (sturdy serif)",
    "category": "serif",
    "family": "Storyloom Merriweather",
    "css": "\"Storyloom Merriweather\", Georgia, serif",
    "files": [
      {
        "file": "merriweather-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "merriweather-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "merriweather-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "merriweather-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "merriweather-800-normal-latin.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "merriweather-800-normal-latin-ext.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "merriweather-800-italic-latin.woff2",
        "weight": 800,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "merriweather-800-italic-latin-ext.woff2",
        "weight": 800,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "playfair",
    "label": "Playfair (fancy titles)",
    "category": "serif",
    "family": "Storyloom Playfair Display",
    "css": "\"Storyloom Playfair Display\", Georgia, serif",
    "files": [
      {
        "file": "playfair-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "playfair-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "playfair-400-italic-latin.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "playfair-400-italic-latin-ext.woff2",
        "weight": 400,
        "style": "italic",
        "subset": "latin-ext"
      },
      {
        "file": "playfair-800-normal-latin.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "playfair-800-normal-latin-ext.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "playfair-800-italic-latin.woff2",
        "weight": 800,
        "style": "italic",
        "subset": "latin"
      },
      {
        "file": "playfair-800-italic-latin-ext.woff2",
        "weight": 800,
        "style": "italic",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "bubblegum",
    "label": "Bubblegum (playful)",
    "category": "display",
    "family": "Storyloom Bubblegum Sans",
    "css": "\"Storyloom Bubblegum Sans\", system-ui, sans-serif",
    "files": [
      {
        "file": "bubblegum-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "bubblegum-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "luckiest",
    "label": "Luckiest Guy (comic titles)",
    "category": "display",
    "family": "Storyloom Luckiest Guy",
    "css": "\"Storyloom Luckiest Guy\", system-ui, sans-serif",
    "files": [
      {
        "file": "luckiest-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "luckiest-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "sniglet",
    "label": "Sniglet (chunky)",
    "category": "display",
    "family": "Storyloom Sniglet",
    "css": "\"Storyloom Sniglet\", system-ui, sans-serif",
    "files": [
      {
        "file": "sniglet-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "sniglet-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "sniglet-800-normal-latin.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "sniglet-800-normal-latin-ext.woff2",
        "weight": 800,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "patrick",
    "label": "Patrick Hand (handwriting)",
    "category": "handwriting",
    "family": "Storyloom Patrick Hand",
    "css": "\"Storyloom Patrick Hand\", \"Chalkboard SE\", cursive",
    "files": [
      {
        "file": "patrick-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "patrick-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "kalam",
    "label": "Kalam (pen)",
    "category": "handwriting",
    "family": "Storyloom Kalam",
    "css": "\"Storyloom Kalam\", \"Chalkboard SE\", cursive",
    "files": [
      {
        "file": "kalam-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "kalam-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "kalam-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "kalam-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "caveat",
    "label": "Caveat (quick notes)",
    "category": "handwriting",
    "family": "Storyloom Caveat",
    "css": "\"Storyloom Caveat\", \"Chalkboard SE\", cursive",
    "files": [
      {
        "file": "caveat-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "caveat-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "caveat-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "caveat-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  },
  {
    "key": "amatic",
    "label": "Amatic (tall sketch)",
    "category": "handwriting",
    "family": "Storyloom Amatic SC",
    "css": "\"Storyloom Amatic SC\", \"Chalkboard SE\", cursive",
    "files": [
      {
        "file": "amatic-400-normal-latin.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "amatic-400-normal-latin-ext.woff2",
        "weight": 400,
        "style": "normal",
        "subset": "latin-ext"
      },
      {
        "file": "amatic-700-normal-latin.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin"
      },
      {
        "file": "amatic-700-normal-latin-ext.woff2",
        "weight": 700,
        "style": "normal",
        "subset": "latin-ext"
      }
    ]
  }
];
