// Storyloom's fonts: 4 built-in Mac fonts plus the free fonts bundled in renderer/fonts/.
// The bundled list (fonts/fonts-list.js) and @font-face rules (fonts/fonts.css) are generated by
// scripts/fetch-fonts.mjs. This file turns them into:
//   FONTS (key → CSS font-family), FONT_LABEL (key → name), FONT_GROUPS (for pickers),
//   FONT_FILES (key → bundled .woff2 files, for e-books), isFont(key),
//   loadFonts(keys) to wait for fonts before drawing or exporting, bookFontKeys(book), fontOptions(selected).
// Fonts load lazily: a file is only read when text uses it. loadFonts() forces them, so exports never fall back.
(() => {
  'use strict';

  // The original four, built into macOS. Keys are saved in books, so they never change.
  const SYSTEM = [
    ['serif', 'Storybook serif', 'Georgia, "Iowan Old Style", "Times New Roman", serif'],
    ['sans', 'Clean sans', 'system-ui, -apple-system, "Helvetica Neue", Arial, sans-serif'],
    ['rounded', 'Rounded', '"Arial Rounded MT Bold", ui-rounded, "SF Pro Rounded", system-ui, sans-serif'],
    ['hand', 'Hand-drawn', '"Chalkboard SE", "Marker Felt", "Comic Sans MS", cursive'],
  ];
  const GROUP = { serif: 'Book fonts', 'sans-serif': 'Easy-reading fonts', display: 'Title fonts', handwriting: 'Handwriting fonts' };

  const FONTS = {};
  const FONT_LABEL = {};
  const FONT_FILES = {};
  const groups = new Map();
  const add = (key, label, css, group) => {
    FONTS[key] = css;
    FONT_LABEL[key] = label;
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(key);
  };
  for (const [key, label, css] of SYSTEM) add(key, label, css, 'Mac fonts');
  for (const font of window.STORYLOOM_BUNDLED_FONTS || []) {
    if (!/^[a-z0-9-]{1,32}$/.test(font.key) || FONTS[font.key]) continue;
    add(font.key, font.label, font.css, GROUP[font.category] || 'More fonts');
    FONT_FILES[font.key] = { family: font.family, files: font.files.map((f) => ({ ...f, href: `fonts/${f.file}` })) };
  }

  const FONT_GROUPS = [...groups.entries()].map(([label, keys]) => ({ label, keys }));
  const isFont = (key) => typeof key === 'string' && Object.prototype.hasOwnProperty.call(FONTS, key);

  // Waits until every bundled font in `keys` (all its weights and styles) is ready, up to `timeoutMs`.
  // Mac fonts are always ready. Never throws: if a font is slow, the export uses whatever has loaded.
  async function loadFonts(keys, { timeoutMs = 8000 } = {}) {
    const wanted = [...new Set(keys)].filter((key) => FONT_FILES[key]);
    if (!wanted.length || !document.fonts) return true;
    const loads = [];
    for (const key of wanted) {
      const { family, files } = FONT_FILES[key];
      for (const f of files.filter((x) => x.subset === 'latin')) {
        loads.push(document.fonts.load(`${f.style} ${f.weight} 16px "${family}"`, 'BESbswy'));
      }
    }
    let timer;
    const timeout = new Promise((resolve) => { timer = setTimeout(() => resolve(false), timeoutMs); });
    try {
      return await Promise.race([Promise.allSettled(loads).then(() => true), timeout]);
    } finally {
      clearTimeout(timer);
    }
  }

  // Font keys a book uses (page text, page titles, and text elements).
  function bookFontKeys(book) {
    const keys = new Set();
    for (const page of book?.pages || []) {
      if (isFont(page.font)) keys.add(page.font);
      if (isFont(page.titleFont)) keys.add(page.titleFont);
      for (const el of page.elements || []) if (el?.type === 'text' && isFont(el.font)) keys.add(el.font);
    }
    return [...keys];
  }

  // Grouped <option>s for a font <select>; each name is shown in its own font.
  function fontOptions(selected) {
    return FONT_GROUPS.map((group) => h('optgroup', { label: group.label },
      group.keys.map((key) => h('option', { value: key, selected: key === selected, style: { fontFamily: FONTS[key] } }, FONT_LABEL[key]))));
  }

  Object.assign(window, { FONTS, FONT_LABEL, FONT_FILES, FONT_GROUPS, isFont, loadFonts, bookFontKeys, fontOptions });
})();
