// Downloads Storyloom's bundled fonts from Fontsource into renderer/fonts/, with their license files,
// and writes renderer/fonts/fonts.json (exact versions and SHA-256 of every file), plus the two files the
// app loads: renderer/fonts/fonts.css (@font-face rules) and renderer/fonts/fonts-list.js (the font list).
//
//   node scripts/fetch-fonts.mjs          → download (only when the font list changes)
//   node scripts/fetch-fonts.mjs --check  → verify the committed files against fonts.json (no network)
//
// Every font is under the SIL Open Font License 1.1 or Apache 2.0, both of which allow bundling and
// embedding in PDFs and e-books. Only Latin + Latin Extended letters are kept, to keep the app small.
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'renderer', 'fonts');
const API = 'https://api.fontsource.org/v1/fonts/';
const ALLOWED_LICENSES = new Set(['OFL-1.1', 'Apache-2.0']);
const ALLOWED_HOST = 'cdn.jsdelivr.net';

// Storyloom's fonts: key (stored in books), Fontsource id, label, the weights and styles to bundle.
// Keep keys stable: books save them.
export const FONT_LIST = [
  { key: 'andika', id: 'andika', label: 'Andika (easy reading)', weights: [400, 700], styles: ['normal', 'italic'] },
  { key: 'atkinson', id: 'atkinson-hyperlegible', label: 'Atkinson (clear)', weights: [400, 700], styles: ['normal', 'italic'] },
  { key: 'nunito', id: 'nunito', label: 'Nunito (soft sans)', weights: [400, 800], styles: ['normal', 'italic'] },
  { key: 'quicksand', id: 'quicksand', label: 'Quicksand (light round)', weights: [400, 700], styles: ['normal'] },
  { key: 'fredoka', id: 'fredoka', label: 'Fredoka (round)', weights: [400, 700], styles: ['normal'] },
  { key: 'baloo', id: 'baloo-2', label: 'Baloo (bouncy)', weights: [400, 800], styles: ['normal'] },
  { key: 'lora', id: 'lora', label: 'Lora (book serif)', weights: [400, 700], styles: ['normal', 'italic'] },
  { key: 'literata', id: 'literata', label: 'Literata (classic book)', weights: [400, 700], styles: ['normal', 'italic'] },
  { key: 'merriweather', id: 'merriweather', label: 'Merriweather (sturdy serif)', weights: [400, 800], styles: ['normal', 'italic'] },
  { key: 'playfair', id: 'playfair-display', label: 'Playfair (fancy titles)', weights: [400, 800], styles: ['normal', 'italic'] },
  { key: 'bubblegum', id: 'bubblegum-sans', label: 'Bubblegum (playful)', weights: [400], styles: ['normal'] },
  { key: 'luckiest', id: 'luckiest-guy', label: 'Luckiest Guy (comic titles)', weights: [400], styles: ['normal'] },
  { key: 'sniglet', id: 'sniglet', label: 'Sniglet (chunky)', weights: [400, 800], styles: ['normal'] },
  { key: 'patrick', id: 'patrick-hand', label: 'Patrick Hand (handwriting)', weights: [400], styles: ['normal'] },
  { key: 'kalam', id: 'kalam', label: 'Kalam (pen)', weights: [400, 700], styles: ['normal'] },
  { key: 'caveat', id: 'caveat', label: 'Caveat (quick notes)', weights: [400, 700], styles: ['normal'] },
  { key: 'amatic', id: 'amatic-sc', label: 'Amatic (tall sketch)', weights: [400, 700], styles: ['normal'] },
];
const SUBSETS = ['latin', 'latin-ext'];

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');
// Which characters each file covers, so the browser only loads the file a page actually needs.
const RANGES = {
  latin: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
  'latin-ext': 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
};
const FALLBACK = { serif: 'Georgia, serif', 'sans-serif': 'system-ui, sans-serif', display: 'system-ui, sans-serif', handwriting: '"Chalkboard SE", cursive' };
const familyOf = (font) => font.cssFamily; // "Storyloom <name>": a private name, so it never clashes with installed fonts

// fonts.css and fonts-list.js, both derived from fonts.json.
function generated(manifest) {
  const css = ['/* Generated by scripts/fetch-fonts.mjs from fonts.json. Do not edit. */'];
  const list = [];
  for (const font of manifest.fonts) {
    for (const f of font.files) {
      css.push(`@font-face { font-family: "${familyOf(font)}"; src: url("${f.file}") format("woff2"); font-weight: ${f.weight}; font-style: ${f.style}; font-display: swap; unicode-range: ${RANGES[f.subset]}; }`);
    }
    list.push({
      key: font.key, label: font.label, category: font.category, family: familyOf(font),
      css: `"${familyOf(font)}", ${FALLBACK[font.category] || 'system-ui, sans-serif'}`,
      files: font.files.map((f) => ({ file: f.file, weight: f.weight, style: f.style, subset: f.subset })),
    });
  }
  return {
    css: `${css.join('\n')}\n`,
    js: `// Generated by scripts/fetch-fonts.mjs from fonts.json. Do not edit.\nwindow.STORYLOOM_BUNDLED_FONTS = ${JSON.stringify(list, null, 2)};\n`,
  };
}

async function get(url, as = 'json') {
  const parsed = new URL(url);
  if (parsed.protocol !== 'https:' || ![ALLOWED_HOST, 'api.fontsource.org', 'data.jsdelivr.com'].includes(parsed.hostname)) throw new Error(`Refusing to fetch ${url}`);
  const response = await fetch(parsed, { redirect: 'error', signal: AbortSignal.timeout(60000) });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return as === 'json' ? response.json() : Buffer.from(await response.arrayBuffer());
}

async function download() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(path.join(outDir, 'licenses'), { recursive: true });
  const manifest = { source: 'https://fontsource.org', fonts: [] };
  for (const font of FONT_LIST) {
    const info = await get(`${API}${font.id}`);
    const license = typeof info.license === 'object' ? info.license.type : info.license;
    if (!ALLOWED_LICENSES.has(license)) throw new Error(`${font.id} is ${license}, which isn't allowed`);
    // Pin the published @fontsource package version, so every build gets byte-identical files.
    const pkg = await get(`https://data.jsdelivr.com/v1/packages/npm/@fontsource/${font.id}`);
    const version = pkg?.tags?.latest;
    if (!/^\d+\.\d+\.\d+$/.test(String(version))) throw new Error(`${font.id} has no usable package version`);
    const files = [];
    for (const weight of font.weights) {
      for (const style of font.styles) {
        for (const subset of SUBSETS) {
          const variant = info.variants?.[String(weight)]?.[style]?.[subset];
          if (!variant) {
            if (subset === 'latin') throw new Error(`${font.id} has no ${weight} ${style} latin file`);
            continue; // some fonts have no latin-ext
          }
          if (!variant.url?.woff2) throw new Error(`${font.id} has no woff2 file for ${weight} ${style} ${subset}`);
          const url = `https://cdn.jsdelivr.net/npm/@fontsource/${font.id}@${version}/files/${font.id}-${subset}-${weight}-${style}.woff2`;
          const data = await get(url, 'buffer');
          const file = `${font.key}-${weight}-${style}-${subset}.woff2`;
          await writeFile(path.join(outDir, file), data);
          files.push({ file, weight, style, subset, unicodeRange: RANGES[subset], sha256: sha256(data), size: data.length, url });
        }
      }
    }
    const licenseUrl = `https://cdn.jsdelivr.net/npm/@fontsource/${font.id}@${version}/LICENSE`;
    const licenseText = await get(licenseUrl, 'buffer');
    await writeFile(path.join(outDir, 'licenses', `${font.key}.txt`), licenseText);
    manifest.fonts.push({ key: font.key, id: font.id, family: info.family, cssFamily: `Storyloom ${info.family}`, label: font.label, category: info.category, license, version, files,
      licenseFile: `licenses/${font.key}.txt`, licenseSha256: sha256(licenseText) });
    console.log(`${font.key}: ${info.family} ${version} (${license}), ${files.length} files`);
  }
  await writeFile(path.join(outDir, 'fonts.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  const out = generated(manifest);
  await writeFile(path.join(outDir, 'fonts.css'), out.css);
  await writeFile(path.join(outDir, 'fonts-list.js'), out.js);
}

async function check() {
  const manifest = JSON.parse(await readFile(path.join(outDir, 'fonts.json'), 'utf8'));
  const expected = new Set(['fonts.json', 'fonts.css', 'fonts-list.js', 'licenses']);
  const out = generated(manifest);
  if (await readFile(path.join(outDir, 'fonts.css'), 'utf8') !== out.css) throw new Error('fonts.css is out of date: run node scripts/fetch-fonts.mjs');
  if (await readFile(path.join(outDir, 'fonts-list.js'), 'utf8') !== out.js) throw new Error('fonts-list.js is out of date: run node scripts/fetch-fonts.mjs');
  for (const font of manifest.fonts) {
    for (const f of font.files) {
      expected.add(f.file);
      const data = await readFile(path.join(outDir, f.file));
      if (sha256(data) !== f.sha256) throw new Error(`${f.file} doesn't match fonts.json`);
    }
    if (sha256(await readFile(path.join(outDir, font.licenseFile))) !== font.licenseSha256) throw new Error(`${font.licenseFile} doesn't match fonts.json`);
  }
  const extra = (await readdir(outDir)).filter((name) => !expected.has(name));
  if (extra.length) throw new Error(`Unexpected files in renderer/fonts: ${extra.join(', ')}`);
  console.log(`${manifest.fonts.length} fonts match fonts.json`);
}

if (process.argv.includes('--check')) await check();
else await download();
